services:
- type: web
  name: line-bot-python-flask
  env: python
  repo: https://github.com/Ricepaste/LINEBOT
  buildCommand: pip install gunicorn -r requirements.txt
  startCommand: gunicorn LINEBOT_NPC:app
  plan: free
  autoDeploy: false
  envVars:
  - key: LINE_CHANNEL_ACCESS_TOKEN
    sync: false
  - key: LINE_CHANNEL_SECRET
    sync: false
